# Default Profile
spring:
  application:
    name: spring-boot-demo
  profiles:
    active: default

server:
  port: 8080

profile:
  name: Default

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: spring-boot-demo-dev

server:
  port: 8080

profile:
  name: Development

---
# Staging Profile
spring:
  config:
    activate:
      on-profile: stage
  application:
    name: spring-boot-demo-stage

server:
  port: 8083

profile:
  name: Staging

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod
  application:
    name: spring-boot-demo-prod

server:
  port: 8082

profile:
  name: Production
